### ISSUE TITLE
Does any plan to release the pretrain code?

### ISSUE THREAD

**Issue by RyanHuangNLP** [microsoft/DeBERTa#11]
Is there any plan to open source pre-trained model code that can train deberta in different languages.

**Comment by guotong1988** [comment]
Same question.

**Comment by dvsrepo** [comment]
Any news regarding this question? We are also interested

**Comment by peregilk** [comment]
We are ready to start pre-training a large language model from scratch for another language in about a month. We are currently considering if we should base this on BERT/RoBERTa/DeBERTa. Any news on the status on the release of the pre-training code? Is it reasonable to expect it in the next weeks?

**Comment by BigBird01** [comment]
We already released the pre-training code in our experiments/language_model folder. Please check it.
