### ISSUE TITLE
 No module named 'torch._six'

### ISSUE THREAD

**Issue by StephennFernandes** [microsoft/DeBERTa#128]
Ive been trying to run the pretraining script on deverta small on the basic wiki datasets that configured to be run inside rtd.sh 
i have just clone the repo installed everything and ran `bash rtd.sh debertav3-xsmall`

But i have been running torch._six error

the following is the error:
```
from torch._six import string_classes, int_classes, FileNotFoundError
ModuleNotFoundError: No module named 'torch._six'
```
ive upgraded pytorch to 2.0 form 1.12 but the issue still persists. in 1.12 only the int_classes was not found but in pytorch 2.0 six has been deprecated i guess.

**Comment by StephennFernandes** [comment]
UPDATE: been able to mitingate from the following error by just adding the following likes and commenting out the torch._six line. 

```
#from torch._six import string_classes, int_classes, FileNotFoundError
import six
string_classes = six.string_types
int_classes = (int,)
import sys
if sys.version_info[0] >= 3:
    FileNotFoundError = FileNotFoundError
else:
    FileNotFoundError = OSError
```
however been stuck now on this: #129

**Comment by StephennFernandes** [comment]
Looks like there was an older repo of DeBERTa inside my  python site-packages that was causing all the issues. 

Hence closing

**Comment by Rishik00** [comment]
Hey I have been trying to do the same, however it keeps giving me the same error. Are there any steps that I should follow after making these changes?
