### ISSUE TITLE
AssertionError: RTD is not registed.

### ISSUE THREAD

**Issue by StephennFernandes** [microsoft/DeBERTa#129]
upon running the pretraining script `bash rtd.sh deberta-v3-xsmall ` i get the following error:

```
assert values.lower() in all_tasks, f'{values} is not registed. Valid tasks {list(all_tasks.keys())}'
AssertionError: RTD is not registed. Valid tasks ['sts-b', 'rte', 'mrpc', 'qnli', 'cola', 'sst-2', 'qqp', 'mnli', 'anli', 'race', 'ner']
```
gently pinging @BigBird01

**Comment by StephennFernandes** [comment]
closing as it was just some weird import issue that was causing all this

**Comment by RuilingZ** [comment]
> upon running the pretraining script `bash rtd.sh deberta-v3-xsmall ` i get the following error:
> 
> ```
> assert values.lower() in all_tasks, f'{values} is not registed. Valid tasks {list(all_tasks.keys())}'
> AssertionError: RTD is not registed. Valid tasks ['sts-b', 'rte', 'mrpc', 'qnli', 'cola', 'sst-2', 'qqp', 'mnli', 'anli', 'race', 'ner']
> ```
> 
> gently pinging @BigBird01

Can I ask how did you solve this problem? I have the same error as this when I run `bash rtd.sh deberta-v3-xsmall`. Thank you so much!

**Comment by Eric-Chen-007** [comment]
> > upon running the pretraining script `bash rtd.sh deberta-v3-xsmall ` i get the following error:
> > ```
> > assert values.lower() in all_tasks, f'{values} is not registed. Valid tasks {list(all_tasks.keys())}'
> > AssertionError: RTD is not registed. Valid tasks ['sts-b', 'rte', 'mrpc', 'qnli', 'cola', 'sst-2', 'qqp', 'mnli', 'anli', 'race', 'ner']
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > gently pinging @BigBird01
> 
> Can I ask how did you solve this problem? I have the same error as this when I run `bash rtd.sh deberta-v3-xsmall`. Thank you so much!

Hi, I have the same problem, have you solved this promblem?
