### ISSUE TITLE
Pre-trained models are not accessible

### ISSUE THREAD

**Issue by ashissamal** [microsoft/DeBERTa#17]
Thanks for sharing the repo. However, I could not access the per-trained base and large models from the below paths.

https://github.com/microsoft/DeBERTa/releases/download/v0.1/base.zip
https://github.com/microsoft/DeBERTa/releases/download/v0.1/large.zip

**Comment by percent4** [comment]
me too.

**Comment by GraphGrailAi** [comment]
I confirm that, any help?

**Comment by brianweet** [comment]
Try the links on the releases page: https://github.com/microsoft/DeBERTa/releases

https://github.com/microsoft/DeBERTa/releases/download/v0.1.8/base.zip
https://github.com/microsoft/DeBERTa/releases/download/v0.1.8/large.zip

**Comment by BigBird01** [comment]
Our models are released on HF model hubs now. Please [check](https://huggingface.co/models?search=microsoft%2Fdeberta)
