### ISSUE TITLE
Deberta Xlarge

### ISSUE THREAD

**Issue by aabayarea** [microsoft/DeBERTa#25]
Hello there, 

Is Deberta X-large the same model as Deberta1.5B?
https://github.com/microsoft/DeBERTa/releases/tag/v0.1.8

**Comment by chessgecko** [comment]
Doesn't seem like it, the paper says:

> The model consists of 48 layers with a hidden size of 1,536 and 24 attention heads

but the config in xlarge has

`
{
  "hidden_size": 1024,
  "intermediate_size": 4096,
  "num_attention_heads": 16,
  "num_hidden_layers": 48,
}

`

**Comment by BigBird01** [comment]
No. We just release our models of different sizes on huggineface [model hub](https://huggingface.co/models?search=microsoft%2Fdeberta). You can try our moles with our code now. **Please refer readme examples to get started.**
