### ISSUE TITLE
Speed of DeBERTa seems disappointing

### ISSUE THREAD

**Issue by shenfe** [microsoft/DeBERTa#36]
The training or inference speed of deberta is much slower than roberta. Is there any official benchmark on model speed?
And I wonder if the extra computation is inescapable, is it more rewarding that I just increase the number of transformer layers instead of using deberta? The idea of deberta still makes sense of course, but making model deeper is very reliable and more considerable if I expect a better model performance.

**Comment by guotong1988** [comment]
Good question.
