### ISSUE TITLE
"deberta-v2-xxlarge"-Model not working!

### ISSUE THREAD

**Issue by kinimod23** [microsoft/DeBERTa#39]
I do:
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("microsoft/deberta-v2-xxlarge")
model = AutoModel.from_pretrained("microsoft/deberta-v2-xxlarge")

But always the same error occurs:
config_class = CONFIG_MAPPING[config_dict["model_type"]]
KeyError: 'deberta-v2'

Appreciate your help!

**Comment by BigBird01** [comment]
You may need to sync the latest transformers code and pip install from source.

**Comment by Oxi84** [comment]
I found that no Deberta model works, they just provide random predictions. Complete waste of time.
