### ISSUE TITLE
A question about the Attention map

### ISSUE THREAD

**Issue by 14H034160212** [microsoft/DeBERTa#44]
Hi,

I have a question about the Attention Map. What is the meaning of the x-axis and y-axis? Does that mean the Attention head?
![image](https://user-images.githubusercontent.com/23516191/111600019-d4d05780-8835-11eb-9558-1a8ccd0a7504.png)

Kind regards,
Qiming

**Comment by BigBird01** [comment]
x,y are the position of different tokens in the sequence, e.g.,

[CLS] Deep learning is magic. [SEP]
0        1       2            3  4         5

Thanks!
