### ISSUE TITLE
The amount of WSC training examples

### ISSUE THREAD

**Issue by slowwavesleep** [microsoft/DeBERTa#45]
Hi,

According to the table in the appendix to the paper, 554 thousand (!) examples were used to train the DeBERTa model on the WSC task. Winograd Schemas are generally not very easy to come up with, especially such a huge amount. Can you please clarify where do these training examples come from? Or is it just a typo? See the screenshot of the table below.

![image](https://user-images.githubusercontent.com/44175589/111838215-0fa3bf80-890a-11eb-941f-8be25ad51297.png)

**Comment by BigBird01** [comment]
Thanks for the catch up. It's typo. We will fix it in our updated version of the paper.
