### ISSUE TITLE
About Enhanced Masked Decoding 

### ISSUE THREAD

**Issue by JXZe** [microsoft/DeBERTa#56]
I cannot find the coding about Enhanced Masked Decoding, can you explain where is the related coding?

**Comment by JXZe** [comment]
The code has been updated.

**Comment by tjshu** [comment]
sorry,I can not find Enhanced Masked Decoding.where is it?

**Comment by tjshu** [comment]
> The code has been updated.
sorry,I can not find Enhanced Masked Decoding.where is it?

**Comment by JXZe** [comment]
> > The code has been updated.
> > sorry,I can not find Enhanced Masked Decoding.where is it?

Click [here](https://github.com/microsoft/DeBERTa/blob/master/DeBERTa/apps/models/masked_language_model.py#L30).

**Comment by tjshu** [comment]
thank for reply!
