### ISSUE TITLE
How to get sentence embedding from DeBERTa for SNLI Dataset?

### ISSUE THREAD

**Issue by akshat-suwalka** [microsoft/DeBERTa#60]
Hi,
I want a single vector from hugging face DeBERTA-base model for doing semantic similarity....
Can i use the first vector of DeBERTa to represent the whole sentence OR Can i use the sum of first and last vector to represent sentence embedding???
Can anybody guide me how to use deberta to get the accuracy on snli dataset??

Thanks

**Comment by BigBird01** [comment]
You can use either of them based on our evaluation results. Generally, we use the first token, i.e. [CLS].
