### ISSUE TITLE
Can't load DeBERTa-v3 tokenizer

### ISSUE THREAD

**Issue by maiiabocharova** [microsoft/DeBERTa#70]
```
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("microsoft/deberta-v3-base")
```
Gives me an error
ValueError: This tokenizer cannot be instantiated. Please make sure you have `sentencepiece` installed in order to use this tokenizer.
But sentencepiece is already installed

Also tried 
```
!pip install deberta
from DeBERTa import deberta
vocab_path, vocab_type = deberta.load_vocab(pretrained_id='base-v3')
tokenizer = deberta.tokenizers[vocab_type](vocab_path)
```
this gives me 
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

Please help, how can I use the tokenizer for deberta-base-v3?

**Comment by chrischowfy** [comment]
> 
from transformers import DebertaV2Tokenizer, DebertaV2Model
tokenizer = DebertaV2Tokenizer.from_pretrained("microsoft/deberta-v3-base")
is work for me.

**Comment by maiiabocharova** [comment]
> > 
> 
> from transformers import DebertaV2Tokenizer, DebertaV2Model tokenizer = DebertaV2Tokenizer.from_pretrained("microsoft/deberta-v3-base") is work for me.

Thank you, I was able to initialize tokenizer, but later it gives me an error when providing text to tokenizer 
`tokenizer("Some text")`
TypeError: 'NoneType' object is not callable

**Comment by chrischowfy** [comment]
That is weird. 
![image](https://user-images.githubusercontent.com/53136736/143733797-d852b111-0d05-4af9-92ea-d829d77efc35.png)

**Comment by maiiabocharova** [comment]
Hello, the issue was that I used colab and tokenizer needed `sentencepiece` to be installed. So the solution was to install `sentencepiece` and afterwards restart the runtime. (I didn't restart it at first)

Thank you sharing the model!
