### ISSUE TITLE
Need DeBERTa v3 xsmall Huggingface Transformers fastTokenizer for NER

### ISSUE THREAD

**Issue by bluesky333** [microsoft/DeBERTa#79]
I want to try NER for custom dataset using huggingface transformers DeBERTa v3 xsmall.
I need to use fastTokenizer, but it is not available.
The error is with huggingface transformers not implementing DeBERTa v2 fastTokenizer.
I need to use fastTokenizer for the return_offsets_mapping function.

Do you have plans for releasing fastTokenizer for DeBERTa v3 in huggingface transformers?
(From my understanding, currently the example NER config from this repo only supports DeBERT v3 large, 
so if I want to use xsmall, small, or base models I thought I have to use huggingface transformers.
Is this correct?)

When I run the below code,
`train_encodings = tokenizer(train_texts, is_split_into_words=True, return_offsets_mapping=True, padding=True, truncation=True, max_length=MAX_LENGTH)
`

I get the below is the error message:
`NotImplementedError: return_offset_mapping is not available when using Python tokenizers.To use this feature, change your tokenizer to one deriving from transformers.PreTrainedTokenizerFast.
`

**Comment by BigBird01** [comment]
I would suggest you open a feature request on huggingface transformers repo.
